GET http://localhost:8888/licensing-service/default
Content-Type: application/json

###
GET http://localhost:8888/licensing-service/dev
Content-Type: application/json

###
GET http://localhost:8888/licensing-service/prod
Content-Type: application/json

###
GET http://localhost:8888/fl/default
Content-Type: application/json

###
GET http://localhost:8888/fl/dev
Content-Type: application/json

###
GET http://localhost:8888/fl/prod
Content-Type: application/json

###
POST http://localhost:8888/encrypt
Content-Type: text/plain

postgres

###
POST http://localhost:8888/decrypt
Content-Type: text/plain

17630484811e5df72d81e19158ce9837fb4adf4ba3abbb7c5a6a7b017ac581f3
