version: '3.8'

services:
  config_srv:
    build:
      context: .
      dockerfile: Dockerfile
    image: config-service-app:1.0.1
    container_name: config-service-container
    ports:
      - "8888:8888"
    environment:
      - JAVA_OPTS=-Xms64m -Xmx256m
    volumes:
      - $HOME/profiles-yml:/home/springuser/profiles-yml

#docker save -o config-service-app-1.0.0.tar config-service-app:1.0.0
#docker load -i config-service-app-1.0.0.tar
