version: '3.8'

services:
    config_srv:
        build:
            context: .
            dockerfile: Dockerfile
        image: config-service-app:1.0.1
        container_name: config-service-container
        restart: always
        ports:
            - "8888:8888"
        networks:
            - project_network
        environment:
            - JAVA_OPTS=-Xms64m -Xmx256m
        volumes:
            - $HOME/properties-yml:/home/springuser/properties-yml

networks:
    project_network:
        external: true

# docker network list
# docker network create project_network
# docker network inspect project_network

#docker save -o config-service-app-1.0.0.tar config-service-app:1.0.0
#docker load -i config-service-app-1.0.0.tar
